services:
  db:
    image: postgres:18
    container_name: consultation_booking_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: consultation_booking_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
      - ./backend/sql/schemas.sql:/docker-entrypoint-initdb.d/01-schemas.sql

  backend:
    build: ./backend
    container_name: consultation_booking_backend
    depends_on:
      - db
    environment:
      PORT: 3000
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: consultation_booking_db
      CLIENT_URL: http://localhost:3001
    ports:
      - "3000:3000"

  frontend:
    build:
      context: ./frontend
      args:
        NEXT_PUBLIC_API_URL: http://localhost:3000/api
    container_name: consultation_booking_frontend
    depends_on:
      - backend
    ports:
      - "3001:3001"

volumes:
  postgres_data:
